import pandas as pd
import joblib

attack_feature_vector = {
    "duration": 0,
    "src_bytes": 5000,             
    "dst_bytes": 6000,             
    "wrong_fragment": 3,           
    "urgent": 0,
    "hot": 20,                     
    "num_failed_logins": 5,        
    "logged_in": 0,
    "num_compromised": 4,          
    "root_shell": 1,               
    "su_attempted": 1,
    "num_root": 2,
    "num_access_files": 10,        
    "num_outbound_cmds": 0,
    "is_guest_login": 0,
    "count": 200,                  
    "srv_count": 150,              
    "serror_rate": 0.9,            
    "srv_serror_rate": 0.9,
    "rerror_rate": 0.8,
    "srv_rerror_rate": 0.8,
    "same_srv_rate": 0.1,
    "diff_srv_rate": 0.95,
    "srv_diff_host_rate": 1.0,
    "dst_host_count": 500,         
    "dst_host_srv_count": 400,     
    "dst_host_same_srv_rate": 0.05,
    "dst_host_diff_srv_rate": 0.95,
    "dst_host_same_src_port_rate": 0.0,
    "dst_host_srv_diff_host_rate": 1.0,
    "dst_host_serror_rate": 0.9,
    "dst_host_srv_serror_rate": 0.9,
    "dst_host_rerror_rate": 0.8,
    "dst_host_srv_rerror_rate": 0.8,
    "protocol_type_icmp": 0,
    "protocol_type_tcp": 1,
    "protocol_type_udp": 0,
    "service_IRC": 0,
    "service_Z39_50": 0,
    "service_aol": 0,
    "service_auth": 0,
    "service_bgp": 0,
    "service_courier": 0,
    "service_csnet_ns": 0,
    "service_ctf": 0,
    "service_daytime": 0,
    "service_discard": 0,
    "service_domain": 0,
    "service_domain_u": 0,
    "service_eco_i": 0,
    "service_ecr_i": 0,
    "service_efs": 0,
    "service_exec": 0,
    "service_finger": 0,
    "service_ftp_data": 0,
    "service_gopher": 0,
    "service_harvest": 0,
    "service_hostnames": 0,
    "service_http": 0,
    "service_http_443": 0,
    "service_imap4": 0,
    "service_iso_tsap": 0,
    "service_klogin": 0,
    "service_kshell": 0,
    "service_ldap": 0,
    "service_link": 0,
    "service_login": 0,
    "service_name": 0,
    "service_netbios_dgm": 0,
    "service_netbios_ns": 0,
    "service_netbios_ssn": 0,
    "service_netstat": 0,
    "service_nnsp": 0,
    "service_nntp": 0,
    "service_other": 1,           
    "service_pop_3": 0,
    "service_private": 0,
    "service_remote_job": 0,
    "service_shell": 0,
    "service_smtp": 0,
    "service_sunrpc": 0,
    "service_supdup": 0,
    "service_systat": 0,
    "service_telnet": 0,
    "service_urh_i": 0,
    "service_urp_i": 0,
    "service_uucp": 0,
    "service_uucp_path": 0,
    "service_vmnet": 0,
    "service_whois": 0,
    "flag_REJ": 0,
    "flag_RSTO": 0,
    "flag_RSTOS0": 0,
    "flag_RSTR": 1,
    "flag_S0": 0,
    "flag_S1": 0,
    "flag_S2": 0,
    "flag_S3": 0,
    "flag_SF": 0,
    "flag_SH": 0
}



df_attack = pd.DataFrame([attack_feature_vector])

selected_features = ['duration', 'src_bytes', 'dst_bytes', 'wrong_fragment', 'urgent', 'hot', 
                     'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell', 'su_attempted', 
                     'num_root', 'num_access_files', 'num_outbound_cmds', 'is_guest_login', 'count', 
                     'srv_count', 'serror_rate', 'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 
                     'same_srv_rate', 'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count', 
                     'dst_host_srv_count', 'dst_host_same_srv_rate', 'dst_host_diff_srv_rate', 
                     'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate', 'dst_host_serror_rate', 
                     'dst_host_srv_serror_rate', 'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 
                     'protocol_type_icmp', 'protocol_type_tcp', 'protocol_type_udp', 
                     'service_IRC', 'service_Z39_50', 'service_aol', 'service_auth', 'service_bgp', 
                     'service_courier', 'service_csnet_ns', 'service_ctf', 'service_daytime', 
                     'service_discard', 'service_domain', 'service_domain_u', 'service_eco_i', 
                     'service_ecr_i', 'service_efs', 'service_exec', 'service_finger', 'service_ftp_data', 
                     'service_gopher', 'service_harvest', 'service_hostnames', 'service_http', 
                     'service_http_443', 'service_imap4', 'service_iso_tsap', 'service_klogin', 
                     'service_kshell', 'service_ldap', 'service_link', 'service_login', 'service_name', 
                     'service_netbios_dgm', 'service_netbios_ns', 'service_netbios_ssn', 'service_netstat', 
                     'service_nnsp', 'service_nntp', 'service_other', 'service_pop_3', 'service_private', 
                     'service_remote_job', 'service_shell', 'service_smtp', 'service_sunrpc', 
                     'service_supdup', 'service_systat', 'service_telnet', 'service_urh_i', 'service_urp_i', 
                     'service_uucp', 'service_uucp_path', 'service_vmnet', 'service_whois', 'flag_REJ', 
                     'flag_RSTO', 'flag_RSTOS0', 'flag_RSTR', 'flag_S0', 'flag_S1', 'flag_S2', 'flag_S3', 
                     'flag_SF', 'flag_SH']

df_attack = df_attack[selected_features]


with open('Random_Forest_model.pkl', 'rb') as f:
    model = joblib.load(f)


prediction = model.predict(df_attack)
print("Prediction for attack sample:", prediction[0])
